FROM ubuntu

MAINTAINER Ajaya Shrestha <akiajaya1@gmail.com>

RUN apt-get update && apt-get install -y apache2 && apt-get clean && rm -rf /var/lib/apt/lists/*



MAINTAINER Ajaya Shrestha <akiajaya1@gmail.com>



CMD echo "Here we go again"




